"""What both code emitters share: literal formatting, the header, and the register of every
double the generated code declares (replayed by both suites as a bit-exactness check)."""
import math

from .model import bits_of

HEADER = "Generated by tools/generate-data.py from shared/data/ — do not edit; run the generator."


def double_lit(value):
    v = float(value)
    if not math.isfinite(v):
        raise ValueError(f"non-finite constant {v!r}")
    return repr(v)


class Bits:
    """Every double declared in generated code, with how each platform names it. The generated
    tests assert each constant's bit pattern, so a toolchain that parsed a literal differently
    would turn the suite red instead of drifting the simulation."""

    def __init__(self):
        self.rows = []

    def add(self, expr, value):
        self.rows.append((expr, bits_of(value)))
