"""The declared record families (shared/data/*.toml): loads a declaration and emits the record
types with their canonical JSON encoding and strict decoding, for both platforms.

Two families are declared today — the save (`save.py`, spec §15) and the device record
(`telemetry.py`, spec §17). They are the same shape of thing, so they are one engine and two
tables: a field added to either cannot be spelled differently on the two platforms, because
neither platform spells it (ADR 0009).

The JSON runtime both emitters call — the value tree, the parser, the canonical writer, the
per-type helpers and the typed decode error — is hand-written once on each platform (Season/ in
SmashCore, core/season on Android); the hand-written rule checks a record opts into with
`_validate = true` live beside the family that declares them. Everything a record's shape decides
is generated here, once.
"""
import re
import tomllib
from dataclasses import dataclass

from .common import HEADER
from .model import DataError, camel, fail, upper_snake

# Base types: (Swift type, Kotlin type). Keyed types are enums written as their declared key.
BASE = {
    "int": ("Int", "Int"), "bool": ("Bool", "Boolean"), "string": ("String", "String"),
    "i64": ("Int64", "Long"), "uuid": ("String", "String"),
    "u64": ("UInt64", "Long"), "double": ("Double", "Double"), "rgb": ("UInt32", "Int"),
}
# Enums declared elsewhere in shared/data/ and generated by another emitter — named here, never
# redeclared. `sport` is rules.toml's (field | ice); redeclaring it in telemetry.toml would be a
# second spelling of the same two values, which is the duplication this whole file exists to kill.
KEYED = {"club": "Club", "world": "World", "formation": "Formation", "drill": "Drill", "team": "TeamKey",
         "sport": "Sport"}


@dataclass
class Declaration:
    """One family of records: where it is declared, what it is called, and where it is written."""
    toml: str            # under shared/data/
    format: str          # the generated format object (Swift enum / Kotlin object)
    format_doc: str      # how that object names itself
    swift_path: str
    kotlin_path: str
    swift_doc: str       # the two comment lines under the generated-file header
    kotlin_doc: str
    kotlin_imports: list  # fully-qualified, in the order Kotlin wants them
    sql_path: str = ""       # the DDL for the `_table` records, if any
    contract_path: str = ""  # the collector's machine-readable column contract


@dataclass
class TypeRef:
    name: str          # a base type, a keyed type, a declared enum, or a record name
    is_list: bool
    optional: bool
    record: bool
    enum: bool = False   # declared in this file's [enum.*] rather than elsewhere


@dataclass
class Record:
    name: str
    doc: str
    validate: bool
    fields: list       # [(snake name, TypeRef)]
    table: str = ""    # `_table`: this record is a row in that table (spec §18)
    envelope: bool = False   # `_envelope`: a fragment prepended to every table, never a table itself
    own: list = None   # a table's own fields, without the envelope's — the body a call site fills in
    envelope_name: str = ""  # the record whose fields were prepended


@dataclass
class Enum:
    """A declared set of values: a real enum on both platforms, a CHECK constraint in the DDL."""
    name: str
    doc: str
    values: list


@dataclass
class Family:
    version: int
    records: list
    enums: list
    # The wire contract's own version (spec §18.6), for a declaration that has tables. Deliberately
    # NOT `version`: the file format of a record on a phone and the column set four tables are sent
    # under are two contracts, and a change to one must not be able to move the other.
    wire_version: int = 0

    @property
    def tables(self):
        return [r for r in self.records if r.table]


def load(root, decl):
    path = root / "shared" / "data" / decl.toml
    if not path.exists():
        raise DataError(f"{path} is missing")
    with open(path, "rb") as f:
        doc = tomllib.load(f)
    if not {"format", "record"} <= set(doc) or set(doc) - {"format", "record", "enum", "wire"}:
        fail(decl.toml, f"expected [format], [record.*] and optionally [enum.*] and [wire], got {sorted(doc)}")
    fmt = doc["format"]
    if set(fmt) != {"version"} or isinstance(fmt["version"], bool) or not isinstance(fmt["version"], int) \
            or fmt["version"] < 1:
        fail(f"{decl.toml} [format]", "expected version = a positive integer")
    wire = doc.get("wire")
    if wire is not None and (set(wire) != {"version"} or isinstance(wire["version"], bool)
                             or not isinstance(wire["version"], int) or wire["version"] < 1):
        fail(f"{decl.toml} [wire]", "expected version = a positive integer")
    enums = []
    for name, table in doc.get("enum", {}).items():
        w = f"{decl.toml} [enum.{name}]"
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name):
            fail(w, "an enum name is UpperCamelCase")
        if name in KEYED.values():
            fail(w, f"{name} is already declared elsewhere in shared/data/ — name it, do not redeclare it")
        if set(table) - {"_doc", "values"} or not isinstance(table.get("values"), list):
            fail(w, "expected values = [\"…\"] and an optional _doc")
        doc_text = table.get("_doc")
        if not isinstance(doc_text, str) or not doc_text:
            fail(w, "missing _doc")
        values = table["values"]
        if not values or len(set(values)) != len(values):
            fail(w, "values must be a non-empty list with no duplicates")
        for v in values:
            if not isinstance(v, str) or not re.fullmatch(r"[a-z][A-Za-z0-9]*", v):
                fail(w, f"value {v!r} is lowerCamelCase — it is a wire value and a case name at once")
        enums.append(Enum(name, doc_text, values))
    enum_names = {e.name for e in enums}

    names = list(doc["record"])
    records = []
    for name in names:
        w = f"{decl.toml} [record.{name}]"
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name):
            fail(w, "a record name is UpperCamelCase")
        table = doc["record"][name]
        doc_text = table.get("_doc")
        if not isinstance(doc_text, str) or not doc_text:
            fail(w, "missing _doc")
        validate = table.get("_validate", False)
        if not isinstance(validate, bool):
            fail(w, "_validate must be true or false")
        extra = {k for k in table if k.startswith("_")} - {"_doc", "_validate", "_table", "_envelope"}
        if extra:
            fail(w, f"unknown metadata {sorted(extra)}")
        table_name = table.get("_table", "")
        if not isinstance(table_name, str):
            fail(w, "_table must be the table's name")
        if table_name and not re.fullmatch(r"[a-z][a-z0-9_]*", table_name):
            fail(w, "a table name is lower snake_case")
        is_envelope = table.get("_envelope", False)
        if not isinstance(is_envelope, bool):
            fail(w, "_envelope must be true or false")
        if is_envelope and table_name:
            fail(w, "the envelope is a fragment of every table, never a table of its own")
        fields = []
        for key, text in table.items():
            if key.startswith("_"):
                continue
            fw = f"{w}.{key}"
            if not re.fullmatch(r"[a-z][a-z0-9]*(_[a-z0-9]+)*", key):
                fail(fw, "a field name is snake_case")
            ref = type_ref(text, fw, names, enum_names)
            # A wire row carries no doubles and no colours: the canonical writer encodes both as exact
            # bit patterns (a JSON string), which the collector's contract types as a number — a row it
            # would reject in full. Say it in milliseconds, or in whatever integer the column means.
            if table_name and ref.name in ("double", "rgb"):
                fail(fw, f"a table field may not be a {ref.name} — the canonical encoding is a string "
                         "of its exact bits, and the collector's column is a number; use an integer")
            fields.append((key, ref))
        if not fields:
            fail(w, "a record has at least one field")
        records.append(Record(name, doc_text, validate, fields, table_name, is_envelope))
    envelopes = [r for r in records if r.envelope]
    if len(envelopes) > 1:
        fail(decl.toml, "at most one record may be the envelope")
    if envelopes:
        shared = envelopes[0].fields
        for r in records:
            if not r.table:
                continue
            clash = {k for k, _ in shared} & {k for k, _ in r.fields}
            if clash:
                fail(f"{decl.toml} [record.{r.name}]",
                     f"redeclares the envelope's {sorted(clash)} — the envelope is declared once")
            r.own = r.fields
            r.envelope_name = envelopes[0].name
            r.fields = shared + r.fields
    elif any(r.table for r in records):
        fail(decl.toml, "a table needs an envelope record (_envelope = true)")
    # The wire contract versions itself, separately from the record file the declaration also holds.
    if any(r.table for r in records):
        if wire is None:
            fail(decl.toml, "a declaration with tables needs [wire] version — the columns' own contract (§18.6)")
    elif wire is not None:
        fail(decl.toml, "[wire] versions the tables' column contract, and this declaration has none")

    root_record = records[0]
    first = root_record.fields[0]
    if first[0] != "version" or first[1] != TypeRef("int", False, False, False, False):
        fail(f"{decl.toml} [record.{root_record.name}]", "the root record's first field is version = \"int\"")
    return Family(fmt["version"], records, enums, wire["version"] if wire else 0)


def type_ref(text, where, records, enums=frozenset()):
    if not isinstance(text, str):
        fail(where, f"a field's type is a string, got {text!r}")
    m = re.fullmatch(r"\[([A-Za-z0-9]+)\]|([A-Za-z0-9]+)(\?)?", text)
    if not m:
        fail(where, f"type {text!r} is not T, T? or [T]")
    name = m.group(1) or m.group(2)
    ref = TypeRef(name, m.group(1) is not None, m.group(3) is not None, name in records, name in enums)
    # A declared enum behaves exactly like one declared elsewhere: written as its own value.
    if not ref.record and not ref.enum and name not in BASE and name not in KEYED:
        fail(where, f"unknown type {name!r} — a record, an enum, or one of {sorted(BASE) + sorted(KEYED)}")
    return ref


def swift_type(ref):
    base = ref.name if ref.record or ref.enum else (BASE[ref.name][0] if ref.name in BASE else KEYED[ref.name])
    return f"[{base}]" if ref.is_list else (base + "?" if ref.optional else base)


def kotlin_type(ref):
    base = ref.name if ref.record or ref.enum else (BASE[ref.name][1] if ref.name in BASE else KEYED[ref.name])
    return f"List<{base}>" if ref.is_list else (base + "?" if ref.optional else base)


# --- Swift --------------------------------------------------------------------------------------

def swift_encode_one(ref, expr):
    if ref.record:
        return f"{expr}.json()"
    if ref.enum or ref.name in KEYED:
        return f".string({expr}.rawValue)"
    return {"int": f".int({expr})", "bool": f".bool({expr})", "string": f".string({expr})",
            "i64": f"SaveJSON.i64({expr})", "uuid": f"SaveJSON.uuid({expr})",
            "u64": f"SaveJSON.u64({expr})", "double": f"SaveJSON.double({expr})", "rgb": f"SaveJSON.rgb({expr})"}[ref.name]


def swift_decode_one(ref, value, path):
    if ref.record:
        return f"try {ref.name}(json: {value}, at: {path})"
    if ref.enum:
        return f"try SaveJSON.key({value}, at: {path}) as {ref.name}"
    if ref.name in KEYED:
        return f"try SaveJSON.key({value}, at: {path}) as {KEYED[ref.name]}"
    return f"try SaveJSON.{ref.name}({value}, at: {path})"


def swift(decl, family):
    out = [f"// {HEADER}\n// {decl.swift_doc}\n\n"]
    out.append(f"/// {decl.format_doc} ({decl.toml} [format]). A record of any other version is refused, never read.\n")
    out.append(f"public enum {decl.format} {{\n    public static let version: Int = {family.version}\n}}\n")
    for e in family.enums:
        out.append(f"\n/// {e.doc}\npublic enum {e.name}: String, Sendable, Hashable, CaseIterable {{\n")
        out.extend(f"    case {v}\n" for v in e.values)
        out.append("}\n")
    for r in family.records:
        out.append(f"\n/// {r.doc}\npublic struct {r.name}: Sendable, Hashable {{\n")
        for key, ref in r.fields:
            out.append(f"    public var {camel(key)}: {swift_type(ref)}\n")
        params = ", ".join(f"{camel(k)}: {swift_type(t)}" for k, t in r.fields)
        out.append(f"\n    public init({params}) {{\n")
        out.extend(f"        self.{camel(k)} = {camel(k)}\n" for k, _ in r.fields)
        out.append("    }\n}\n\nextension " + r.name + " {\n")
        out.append("    /// This record as its canonical JSON value.\n    func json() -> JSONValue {\n        .object([\n")
        for key, ref in r.fields:
            n = camel(key)
            if ref.is_list:
                enc = f".array({n}.map {{ {swift_encode_one(ref, '$0')} }})"
            elif ref.optional:
                enc = f"{n}.map {{ {swift_encode_one(ref, '$0')} }} ?? .null"
            else:
                enc = swift_encode_one(ref, n)
            out.append(f"            (\"{key}\", {enc}),\n")
        out.append("        ])\n    }\n\n")
        out.append("    /// Decodes the record at `path` (\"$\" for the file's root), failing on anything but its exact shape.\n")
        out.append("    init(json: JSONValue, at path: String) throws(SaveDecodeError) {\n")
        keys = ", ".join(f'"{k}"' for k, _ in r.fields)
        out.append(f"        let o = try SaveJSON.fields(json, at: path, [{keys}])\n")
        for i, (key, ref) in enumerate(r.fields):
            n, p = camel(key), f'path + ".{key}"'
            if ref.is_list:
                out.append(f"        var {n}: {swift_type(ref)} = []\n")
                item_path = p + ' + "[\\(i)]"'
                out.append(f"        for (i, v) in try SaveJSON.array(o[{i}], at: {p}).enumerated() {{\n")
                out.append(f"            {n}.append({swift_decode_one(ref, 'v', item_path)})\n        }}\n")
                out.append(f"        self.{n} = {n}\n")
            elif ref.optional:
                out.append(f"        if case .null = o[{i}] {{ self.{n} = nil }} else {{ self.{n} = {swift_decode_one(ref, f'o[{i}]', p)} }}\n")
            else:
                out.append(f"        self.{n} = {swift_decode_one(ref, f'o[{i}]', p)}\n")
        if r.validate:
            out.append("        try validate(at: path)\n")
        out.append("    }\n")
        out.append(swift_table(r))
        out.append("}\n")
    return "".join(out)


TABLE_DOC = """
    /// The row's own columns, without the envelope's (spec §18.1). This is what a call site fills
    /// in; the envelope is stamped on once per send, so a queued row carries no clock of its own.
"""
ENVELOPE_DOC = """
    /// One row, from the moment it happened and the envelope of the send that carries it.
"""
ENCODED_DOC = """
    /// The canonical JSON this row is sent as (spec §18.6) — byte for byte what the other platform
    /// sends for the same values, which is what makes the two builds' rows one dataset.
"""


def swift_table(r):
    """A table record's body type, its envelope initialiser and its canonical text (spec §18)."""
    if not r.table:
        return ""
    shared = r.fields[: len(r.fields) - len(r.own)]
    out = ["\n    /// The collector's table, and so its route (spec §18.6): `POST <endpoint>/" + r.table + "`.\n",
           f'    public static let table: String = "{r.table}"\n',
           TABLE_DOC, "    public struct Body: Sendable, Hashable {\n"]
    out.extend(f"        public var {camel(k)}: {swift_type(t)}\n" for k, t in r.own)
    params = ", ".join(f"{camel(k)}: {swift_type(t)}" for k, t in r.own)
    out.append(f"\n        public init({params}) {{\n")
    out.extend(f"            self.{camel(k)} = {camel(k)}\n" for k, _ in r.own)
    out.append("        }\n    }\n")
    out.append(ENVELOPE_DOC)
    out.append(f"    public init(_ envelope: {r.envelope_name}, _ body: Body) {{\n        self.init(")
    args = [f"{camel(k)}: envelope.{camel(k)}" for k, _ in shared] + [f"{camel(k)}: body.{camel(k)}" for k, _ in r.own]
    out.append(",\n                  ".join(args))
    out.append(")\n    }\n")
    out.append(ENCODED_DOC)
    out.append("    public func encoded() -> String { json().canonicalText() }\n")
    return "".join(out)


# --- Kotlin -------------------------------------------------------------------------------------

def kotlin_encode_one(ref, expr):
    if ref.record:
        return f"{expr}.toJson()"
    if ref.enum or ref.name in KEYED:
        return f"JsonValue.Str({expr}.key)"
    return {"int": f"JsonValue.Num({expr}.toLong())", "bool": f"JsonValue.Bool({expr})", "string": f"JsonValue.Str({expr})",
            "i64": f"SaveJson.i64({expr})", "uuid": f"SaveJson.uuid({expr})",
            "u64": f"SaveJson.u64({expr})", "double": f"SaveJson.double({expr})", "rgb": f"SaveJson.rgb({expr})"}[ref.name]


def kotlin_decode_one(ref, value, path):
    if ref.record:
        return f"{ref.name}.fromJson({value}, {path})"
    if ref.enum or ref.name in KEYED:
        t = ref.name if ref.enum else KEYED[ref.name]
        return f"SaveJson.key({value}, {path}, {t}.entries) {{ it.key }}"
    return f"SaveJson.{ref.name}({value}, {path})"


def kotlin(decl, family):
    imports = "".join(f"import `in`.nann.smashhockey.{i}\n" for i in decl.kotlin_imports)
    out = [f"// {HEADER}\n// {decl.kotlin_doc}\n"
           "package `in`.nann.smashhockey.core.generated\n\n"
           f"{imports}\n"]
    out.append(f"/** {decl.format_doc} ({decl.toml} [format]). A record of any other version is refused, never read. */\n")
    out.append(f"object {decl.format} {{\n    const val version: Int = {family.version}\n}}\n")
    for e in family.enums:
        out.append(f"\n/** {e.doc} */\nenum class {e.name}(val key: String) {{\n")
        out.extend(f"    {upper_snake(v)}(\"{v}\"),\n" for v in e.values)
        out.append("}\n")
    for r in family.records:
        out.append(f"\n/** {r.doc} */\ndata class {r.name}(\n")
        out.extend(f"    val {camel(k)}: {kotlin_type(t)},\n" for k, t in r.fields)
        out.append(") {\n    /** This record as its canonical JSON value. */\n")
        out.append("    fun toJson(): JsonValue = JsonValue.Obj(\n        listOf(\n")
        for key, ref in r.fields:
            n = camel(key)
            if ref.is_list:
                enc = f"JsonValue.Arr({n}.map {{ {kotlin_encode_one(ref, 'it')} }})"
            elif ref.optional:
                enc = f"({n}?.let {{ {kotlin_encode_one(ref, 'it')} }} ?: JsonValue.Null)"
            else:
                enc = kotlin_encode_one(ref, n)
            out.append(f"            \"{key}\" to {enc},\n")
        out.append("        ),\n    )\n\n    companion object {\n")
        out.append("        /** Decodes the record at [path] (\"$\" for the file's root), failing on anything but its exact shape. */\n")
        out.append(f"        fun fromJson(json: JsonValue, path: String): {r.name} {{\n")
        keys = ", ".join(f'"{k}"' for k, _ in r.fields)
        out.append(f"            val o = SaveJson.fields(json, path, listOf({keys}))\n")
        out.append(f"            val record = {r.name}(\n")
        for i, (key, ref) in enumerate(r.fields):
            n, p = camel(key), f'"$path.{key}"'
            if ref.is_list:
                item = kotlin_decode_one(ref, "v", f'"$path.{key}[$i]"')
                dec = f"SaveJson.array(o[{i}], {p}).mapIndexed {{ i, v -> {item} }}"
            elif ref.optional:
                dec = f"o[{i}].let {{ if (it is JsonValue.Null) null else {kotlin_decode_one(ref, 'it', p)} }}"
            else:
                dec = kotlin_decode_one(ref, f"o[{i}]", p)
            out.append(f"                {n} = {dec},\n")
        out.append("            )\n")
        if r.validate:
            out.append("            record.validate(path)\n")
        out.append("            return record\n        }\n")
        if r.table:
            out.append(f"\n        /** The collector's table, and so its route (spec §18.6): `POST <endpoint>/{r.table}`. */\n")
            out.append(f'        const val table: String = "{r.table}"\n')
        out.append("    }\n")
        out.append(kotlin_table(r))
        out.append("}\n")
    return "".join(out)


def kdoc(doc):
    """The same comment as Swift's, as KDoc — one source of wording for the two platforms."""
    lines = [l.strip()[4:] for l in doc.strip("\n").split("\n")]
    out = ["\n    /**\n"] + [f"     * {l}\n" for l in lines] + ["     */\n"]
    return "".join(out)


def kotlin_table(r):
    """A table record's body type, its envelope constructor and its canonical text (spec §18)."""
    if not r.table:
        return ""
    shared = r.fields[: len(r.fields) - len(r.own)]
    out = [kdoc(TABLE_DOC)]
    out.append("    data class Body(\n")
    out.extend(f"        val {camel(k)}: {kotlin_type(t)},\n" for k, t in r.own)
    out.append("    )\n")
    out.append(kdoc(ENVELOPE_DOC))
    out.append(f"    constructor(envelope: {r.envelope_name}, body: Body) : this(\n")
    out.extend(f"        {camel(k)} = envelope.{camel(k)},\n" for k, _ in shared)
    out.extend(f"        {camel(k)} = body.{camel(k)},\n" for k, _ in r.own)
    out.append("    )\n")
    out.append(kdoc(ENCODED_DOC))
    out.append("    fun encoded(): String = toJson().canonicalText()\n")
    return "".join(out)


def emit(root, decl):
    family = load(root, decl)
    return {decl.swift_path: swift(decl, family), decl.kotlin_path: kotlin(decl, family)}
